export const messages = [
    "Bugün güzel bir gün!",
    "Yarın hava yağmurlu olacak.",
    "Hayatın tadını çıkarın!",
    "Mutlu olmayı seçin.",
    "Kitap okumak zamanınızı iyi geçirin.",
    "Spor yapmak sizi zinde tutar.",
    "Güne erken başlamak daha verimli olmanızı sağlar.",
    "Yürüyüş yapmak sağlığınıza iyi gelir.",
    "Sevdiklerinizle vakit geçirmek önemlidir.",
    "Yeni bir şeyler öğrenmek sizi geliştirir.",
    "Müzik dinlemek ruhunuzu dinlendirir.",
    "Doğayla iç içe olmak stresinizi azaltır.",
    "Dostluklarınıza değer verin.",
    "Kendinize zaman ayırın.",
    "Hayallerinizi gerçekleştirmek için adım atın.",
    "Olumlu düşünün.",
    "Her gün bir adım ileriye gitmek önemlidir.",
    "Gülümseyin, çevrenize enerji verin.",
    "Kendinize inanın, başarabilirsiniz!",
    "Hatalarınızdan ders çıkarın.",
    "Sağlığınıza dikkat edin, önemlidir.",
    "Başkalarına yardım etmek size mutluluk verebilir.",
    "Geleceğe umutla bakın.",
    "Sevdiğiniz işi yapın, hayatınızı sevin.",
    "Sorumluluklarınızı zamanında yerine getirin.",
    "Başkalarına saygı gösterin.",
    "Küçük şeylerin keyfini çıkarın.",
    "Hobilerinizle zaman geçirin.",
    "Düzenli uyku alışkanlığı edinin.",
    "Stresten uzak durun, sağlığınıza önem verin.",
    "Başkalarının görüşlerine açık olun.",
    "Geleceği planlayın, hedefler koyun.",
    "Yaratıcı olmak sizi mutlu eder.",
    "Kendinizi keşfedin, yeteneklerinizi geliştirin.",
    "İyi bir dinleyici olun, başkalarını anlamaya çalışın.",
    "Mütevazı olun, her zaman öğrenilecek yeni şeyler vardır.",
    "Çevrenizi temiz tutun, doğayı koruyun.",
    "Gelişim için sürekli okuyun.",
    "Sevdiklerinizle vakit geçirmekten keyif alın.",
    "Günlük hayatın tadını çıkarın.",
    "Spor yapmak sizin için önemlidir.",
    "Hayatınızı organize edin, zamanınızı iyi değerlendirin.",
    "Kendinizi motive edin, hedeflerinize odaklanın.",
    "Kendinize güvenin, yapabilirsiniz!",
    "Başkalarına yardım etmek sizi mutlu eder.",
    "Her gün bir şeyler öğrenin, kendinizi geliştirin.",
    "Yeni insanlar tanımak size yeni bakış açıları kazandırır.",
    "Dostluklarınızı önemseyin, dostluklar sizi güçlendirir.",
    "Her gün bir adım atın, ilerlemeye devam edin.",
];
